# Generated by Django 2.1.4 on 2018-12-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('Invader', models.FileField(blank=True, null=True, upload_to='')),
                ('Defender', models.FileField(blank=True, null=True, upload_to='')),
                ('Projectile', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
