# Generated by Django 2.1.4 on 2018-12-19 16:50

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='Defender',
            new_name='defender',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='Invader',
            new_name='invader',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='Projectile',
            new_name='projectile',
        ),
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AddField(
            model_name='game',
            name='gameref',
            field=models.CharField(default=game.models.Game.pkgen, max_length=8, primary_key=True, serialize=False),
        ),
    ]
