# Generated by Django 2.1.4 on 2018-12-19 17:00

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20181219_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameref',
            field=models.CharField(default=game.models.Game.pkgen, max_length=10, primary_key=True, serialize=False),
        ),
    ]
