# Generated by Django 2.1.4 on 2018-12-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20181219_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='invader',
        ),
        migrations.RemoveField(
            model_name='game',
            name='projectile',
        ),
        migrations.AlterField(
            model_name='game',
            name='defender',
            field=models.ImageField(blank=True, null=True, upload_to='FileField/B2E8ATTGhg'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameref',
            field=models.CharField(default='B2E8ATTGhg', max_length=10, primary_key=True, serialize=False),
        ),
    ]
