# Generated by Django 2.1.4 on 2018-12-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20181219_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='defender',
            field=models.ImageField(blank=True, null=True, upload_to='FileField/xQchxo6yUf'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameref',
            field=models.CharField(default='xQchxo6yUf', max_length=10, primary_key=True, serialize=False),
        ),
    ]
