# Generated by Django 2.1.4 on 2018-12-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20181219_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='defender',
            field=models.FileField(blank=True, null=True, upload_to='media/JHqm9C051G'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameref',
            field=models.CharField(default='JHqm9C051G', max_length=10, primary_key=True, serialize=False),
        ),
    ]
