# Generated by Django 2.1.4 on 2018-12-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20181219_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='defender',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameref',
            field=models.CharField(default='AgoIWA5r2j', max_length=10, primary_key=True, serialize=False),
        ),
    ]
