# Generated by Django 2.1.4 on 2018-12-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20181219_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='defender',
            field=models.FileField(blank=True, null=True, upload_to='media/games/nm4EInPtV3'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameref',
            field=models.CharField(default='nm4EInPtV3', max_length=10, primary_key=True, serialize=False),
        ),
    ]
