# Generated by Django 2.1.4 on 2018-12-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20181219_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='invader',
            field=models.FileField(blank=True, null=True, upload_to='media/games/ampnlOrJsb'),
        ),
        migrations.AddField(
            model_name='game',
            name='projectile',
            field=models.FileField(blank=True, null=True, upload_to='media/games/ampnlOrJsb'),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender',
            field=models.FileField(blank=True, null=True, upload_to='media/games/ampnlOrJsb'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameref',
            field=models.CharField(default='ampnlOrJsb', max_length=10, primary_key=True, serialize=False),
        ),
    ]
