# Generated by Django 2.1.4 on 2018-12-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20181221_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='defender',
            field=models.FileField(blank=True, null=True, upload_to='media/games/1uuORHnM34'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameref',
            field=models.CharField(default='1uuORHnM34', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='invader',
            field=models.FileField(blank=True, null=True, upload_to='media/games/1uuORHnM34'),
        ),
        migrations.AlterField(
            model_name='game',
            name='projectile',
            field=models.FileField(blank=True, null=True, upload_to='media/games/1uuORHnM34'),
        ),
    ]
