# Generated by Django 2.1.4 on 2018-12-26 19:34

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20181223_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='highscores',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='game',
            name='is_nsfw',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_public',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='remove_date',
            field=models.DateTimeField(blank=True, default=game.models.get_remove_date),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender',
            field=models.FileField(blank=True, null=True, upload_to='media/games/wl1DCl0Xej'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameref',
            field=models.CharField(default='wl1DCl0Xej', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='invader',
            field=models.FileField(blank=True, null=True, upload_to='media/games/wl1DCl0Xej'),
        ),
        migrations.AlterField(
            model_name='game',
            name='projectile',
            field=models.FileField(blank=True, null=True, upload_to='media/games/wl1DCl0Xej'),
        ),
    ]
