# Generated by Django 2.1.4 on 2018-12-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20181226_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='defender',
            field=models.ImageField(blank=True, null=True, upload_to='media/games/5ZKZK4UnMZ'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameref',
            field=models.CharField(default='5ZKZK4UnMZ', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='invader',
            field=models.ImageField(blank=True, null=True, upload_to='media/games/5ZKZK4UnMZ'),
        ),
        migrations.AlterField(
            model_name='game',
            name='projectile',
            field=models.ImageField(blank=True, null=True, upload_to='media/games/5ZKZK4UnMZ'),
        ),
    ]
