# Generated by Django 2.1.4 on 2019-01-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20181227_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='defender',
            field=models.ImageField(default='', upload_to='media/games/Qm2j1igZaz'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameref',
            field=models.CharField(default='Qm2j1igZaz', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='invader',
            field=models.ImageField(default='', upload_to='media/games/Qm2j1igZaz'),
        ),
        migrations.AlterField(
            model_name='game',
            name='projectile',
            field=models.ImageField(default='', upload_to='media/games/Qm2j1igZaz'),
        ),
    ]
