# Generated by Django 2.1.4 on 2019-01-03 12:04

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20190102_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='defender',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='media/games/LvKYU9nTPB'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameref',
            field=models.CharField(default='LvKYU9nTPB', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='invader',
            field=models.ImageField(default='', upload_to='media/games/LvKYU9nTPB'),
        ),
        migrations.AlterField(
            model_name='game',
            name='projectile',
            field=models.ImageField(default='', upload_to='media/games/LvKYU9nTPB'),
        ),
    ]
