# Generated by Django 2.1.4 on 2019-01-03 19:55

import colorfield.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20190103_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='projectile',
        ),
        migrations.AddField(
            model_name='game',
            name='projectile_color',
            field=colorfield.fields.ColorField(default='#ffffff', max_length=18),
        ),
        migrations.AlterField(
            model_name='game',
            name='defender',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='media/games/EIWBixVyzZ'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameref',
            field=models.CharField(default='EIWBixVyzZ', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='invader',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='media/games/EIWBixVyzZ'),
        ),
    ]
