# Generated by Django 2.1.4 on 2019-01-03 20:33

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20190103_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='defender_name',
            new_name='invader_name',
        ),
        migrations.AlterField(
            model_name='game',
            name='defender',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='media/games/qqEz7NgfHw'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameref',
            field=models.CharField(default='qqEz7NgfHw', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='invader',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='media/games/qqEz7NgfHw'),
        ),
    ]
